apiversion: apps/v1
kind: Deployment
metadata:  
  name: base-mega-api
spec:  
  replicas: 2  
  selector:    
    matchLabels:      
      app: base-mega-api  
  template:    
    metadata:      
      labels:        
        app: base-mega-api    
    spec:      
      containers:      
        - name: base-mega-api        
          image: base_mega_api:latest    
          imagePullPolicy: ifNotPresent    
          ports:        
          - containerPort: 80