apiversion: v1
kind: Service
metadata:  
  name: base-mega-api-service
spec: 
  type: NodePort
  selector:    
    app: base_mega_api 
  ports:    
    - protocol: TCP      
      port: 80      
      targetPort: 80  
      NodePort: 30007
